### ISSUE TITLE
highlight参数添加后报错

### ISSUE THREAD

**Issue by channg** [OfficialYoungX/paper#2]
```
FATAL duplicated mapping key at line 94, column -157:
    highlight:
    ^
YAMLException: duplicated mapping key at line 94, column -157:
    highlight:
    ^
    at generateError (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at storeMappingPair (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
    at readBlockMapping (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
    at composeNode (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/Users/xuezhiwen/blog/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at Hexo.yamlHelper (/Users/xuezhiwen/blog/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/xuezhiwen/blog/node_modules/hexo/lib/hexo/render.js:60:20
    at tryCatcher (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/xuezhiwen/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by OfficialYoungX** [comment]
@哈哈，由于`highlight`在默认生成的文件中已经存在了。你仔细找找，那个文件里面肯定还有另一个`highlight`，把原先的那几行全部删了就是了。

**Comment by OfficialYoungX** [comment]
@channg
